version: '3.3'

services:
  app:
    build: .
    image: spider
    env_file:
      - .env
    volumes:
      - ./spider/db/files_storage/html_files:/app/spider/db/files_storage/html_files
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
#    environment:
#      POSTGRES_DB: mydb
#      POSTGRES_USER: andrew
#      POSTGRES_PASSWORD: andrew
    ports:
      - 5434:5432
    volumes:
      - ./db_dump:/var/lib/postgresql/data

volumes:
  html_files:
  db_dump:
